### ISSUE TITLE
ADD to HOME

### ISSUE THREAD

**Issue by divyansh-2005** [sl-lab1/SL-lab-MiniProject#10]
Add a link to home page in the navigation bar

**Comment by atharvarakshak** [comment]
bhai ek hi page hai jo ki index.html hai . Jo ki  independently kaam kr skta hai. vo code maine uske liye modify kiya hai taki kisi aur ko link krne ki need na ho. To link krke kya hi krega to usi page pe ghumta rhega

**Comment by atharvarakshak** [comment]
done

**Comment by divyansh-2005** [comment]
It is not working please fix the bug. I am reopening issue.

**Comment by divyansh-2005** [comment]
OK.
